import type { DocConfig } from "@/components/transactions-module";

export const invoiceConfig: DocConfig = {
  kind: "invoice",
  title: "Invoices",
  description: "Customer invoices and receivables.",
  docTable: "invoices",
  linesTable: "invoice_lines",
  numberField: "invoice_number",
  dateField: "invoice_date",
  secondaryDateField: "due_date",
  secondaryDateLabel: "Due date",
  partyField: "customer_id",
  partyTable: "customers",
  partyLabel: "Customer",
  docTypeForNumbering: "invoice",
  fkLinesField: "invoice_id",
  statuses: [
    { value: "draft", label: "Draft" },
    { value: "sent", label: "Sent" },
    { value: "partially_paid", label: "Partially Paid" },
    { value: "paid", label: "Paid" },
    { value: "overdue", label: "Overdue" },
    { value: "cancelled", label: "Cancelled" },
  ],
};

export const billConfig: DocConfig = {
  kind: "bill",
  title: "Bills",
  description: "Vendor bills and payables.",
  docTable: "bills",
  linesTable: "bill_lines",
  numberField: "bill_number",
  dateField: "bill_date",
  secondaryDateField: "due_date",
  secondaryDateLabel: "Due date",
  partyField: "supplier_id",
  partyTable: "suppliers",
  partyLabel: "Supplier",
  docTypeForNumbering: "bill",
  fkLinesField: "bill_id",
  statuses: [
    { value: "draft", label: "Draft" },
    { value: "open", label: "Open" },
    { value: "partially_paid", label: "Partially Paid" },
    { value: "paid", label: "Paid" },
    { value: "overdue", label: "Overdue" },
    { value: "cancelled", label: "Cancelled" },
  ],
};

export const purchaseOrderConfig: DocConfig = {
  kind: "purchase_order",
  title: "Purchase Orders",
  description: "Orders sent to your suppliers.",
  docTable: "purchase_orders",
  linesTable: "purchase_order_lines",
  numberField: "po_number",
  dateField: "po_date",
  secondaryDateField: "expected_date",
  secondaryDateLabel: "Expected date",
  partyField: "supplier_id",
  partyTable: "suppliers",
  partyLabel: "Supplier",
  docTypeForNumbering: "purchase_order",
  fkLinesField: "po_id",
  statuses: [
    { value: "draft", label: "Draft" },
    { value: "approved", label: "Approved" },
    { value: "sent", label: "Sent" },
    { value: "partially_received", label: "Partially Received" },
    { value: "received", label: "Received" },
    { value: "closed", label: "Closed" },
    { value: "cancelled", label: "Cancelled" },
  ],
};

export const creditNoteConfig: DocConfig = {
  kind: "credit_note",
  title: "Credit Notes",
  description: "Customer credit notes issued against invoices or refunds.",
  docTable: "credit_notes",
  linesTable: "credit_note_lines",
  numberField: "credit_note_number",
  dateField: "credit_note_date",
  secondaryDateField: "",
  secondaryDateLabel: "",
  partyField: "customer_id",
  partyTable: "customers",
  partyLabel: "Customer",
  docTypeForNumbering: "credit_note",
  fkLinesField: "credit_note_id",
  statuses: [
    { value: "draft", label: "Draft" },
    { value: "open", label: "Open" },
    { value: "applied", label: "Applied" },
    { value: "void", label: "Void" },
  ],
};
