/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesOrdersRouteImport } from './routes/_authenticated/sales-orders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPaymentsReceivedRouteImport } from './routes/_authenticated/payments-received'
import { Route as AuthenticatedPaymentsMadeRouteImport } from './routes/_authenticated/payments-made'
import { Route as AuthenticatedJournalsRouteImport } from './routes/_authenticated/journals'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryAdjustmentsRouteImport } from './routes/_authenticated/inventory-adjustments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChartOfAccountsRouteImport } from './routes/_authenticated/chart-of-accounts'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedBankingRouteImport } from './routes/_authenticated/banking'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedSuppliersNewRouteImport } from './routes/_authenticated/suppliers.new'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './routes/_authenticated/suppliers.$supplierId'
import { Route as AuthenticatedSettingsLocationsRouteImport } from './routes/_authenticated/settings_.locations'
import { Route as AuthenticatedSettingsQuotesRouteImport } from './routes/_authenticated/settings.quotes'
import { Route as AuthenticatedSalesOrdersNewRouteImport } from './routes/_authenticated/sales-orders_.new'
import { Route as AuthenticatedSalesOrdersSoIdRouteImport } from './routes/_authenticated/sales-orders_.$soId'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes_.new'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes_.$quoteId'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders_.new'
import { Route as AuthenticatedPurchaseOrdersPoIdRouteImport } from './routes/_authenticated/purchase-orders_.$poId'
import { Route as AuthenticatedPaymentsReceivedNewRouteImport } from './routes/_authenticated/payments-received_.new'
import { Route as AuthenticatedPaymentsReceivedPaymentIdRouteImport } from './routes/_authenticated/payments-received_.$paymentId'
import { Route as AuthenticatedPaymentsMadeNewRouteImport } from './routes/_authenticated/payments-made_.new'
import { Route as AuthenticatedPaymentsMadePaymentIdRouteImport } from './routes/_authenticated/payments-made_.$paymentId'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items_.new'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items_.$itemId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices_.new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices_.$invoiceId'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers.new'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedBillsNewRouteImport } from './routes/_authenticated/bills_.new'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills_.$billId'
import { Route as AuthenticatedSuppliersSupplierIdEditRouteImport } from './routes/_authenticated/suppliers.$supplierId_.edit'
import { Route as AuthenticatedSettingsLocationsNewRouteImport } from './routes/_authenticated/settings_.locations_.new'
import { Route as AuthenticatedSalesOrdersSoIdEditRouteImport } from './routes/_authenticated/sales-orders_.$soId_.edit'
import { Route as AuthenticatedQuotesQuoteIdEditRouteImport } from './routes/_authenticated/quotes_.$quoteId_.edit'
import { Route as AuthenticatedItemsItemIdEditRouteImport } from './routes/_authenticated/items_.$itemId_.edit'
import { Route as AuthenticatedInvoicesInvoiceIdEditRouteImport } from './routes/_authenticated/invoices_.$invoiceId_.edit'
import { Route as AuthenticatedCustomersCustomerIdEditRouteImport } from './routes/_authenticated/customers.$customerId_.edit'
import { Route as AuthenticatedSettingsLocationsLocationIdEditRouteImport } from './routes/_authenticated/settings_.locations_.$locationId_.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesOrdersRoute =
  AuthenticatedSalesOrdersRouteImport.update({
    id: '/sales-orders',
    path: '/sales-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsReceivedRoute =
  AuthenticatedPaymentsReceivedRouteImport.update({
    id: '/payments-received',
    path: '/payments-received',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsMadeRoute =
  AuthenticatedPaymentsMadeRouteImport.update({
    id: '/payments-made',
    path: '/payments-made',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalsRoute = AuthenticatedJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryAdjustmentsRoute =
  AuthenticatedInventoryAdjustmentsRouteImport.update({
    id: '/inventory-adjustments',
    path: '/inventory-adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartOfAccountsRoute =
  AuthenticatedChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankingRoute = AuthenticatedBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersNewRoute =
  AuthenticatedSuppliersNewRouteImport.update({
    id: '/suppliers/new',
    path: '/suppliers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLocationsRoute =
  AuthenticatedSettingsLocationsRouteImport.update({
    id: '/settings_/locations',
    path: '/settings/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsQuotesRoute =
  AuthenticatedSettingsQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSalesOrdersNewRoute =
  AuthenticatedSalesOrdersNewRouteImport.update({
    id: '/sales-orders_/new',
    path: '/sales-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersSoIdRoute =
  AuthenticatedSalesOrdersSoIdRouteImport.update({
    id: '/sales-orders_/$soId',
    path: '/sales-orders/$soId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes_/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/quotes_/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders_/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersPoIdRoute =
  AuthenticatedPurchaseOrdersPoIdRouteImport.update({
    id: '/purchase-orders_/$poId',
    path: '/purchase-orders/$poId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsReceivedNewRoute =
  AuthenticatedPaymentsReceivedNewRouteImport.update({
    id: '/payments-received_/new',
    path: '/payments-received/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsReceivedPaymentIdRoute =
  AuthenticatedPaymentsReceivedPaymentIdRouteImport.update({
    id: '/payments-received_/$paymentId',
    path: '/payments-received/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsMadeNewRoute =
  AuthenticatedPaymentsMadeNewRouteImport.update({
    id: '/payments-made_/new',
    path: '/payments-made/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsMadePaymentIdRoute =
  AuthenticatedPaymentsMadePaymentIdRouteImport.update({
    id: '/payments-made_/$paymentId',
    path: '/payments-made/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items_/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items_/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices_/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices_/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsNewRoute = AuthenticatedBillsNewRouteImport.update({
  id: '/bills_/new',
  path: '/bills/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills_/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdEditRoute =
  AuthenticatedSuppliersSupplierIdEditRouteImport.update({
    id: '/suppliers/$supplierId_/edit',
    path: '/suppliers/$supplierId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLocationsNewRoute =
  AuthenticatedSettingsLocationsNewRouteImport.update({
    id: '/settings_/locations_/new',
    path: '/settings/locations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersSoIdEditRoute =
  AuthenticatedSalesOrdersSoIdEditRouteImport.update({
    id: '/sales-orders_/$soId_/edit',
    path: '/sales-orders/$soId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesQuoteIdEditRoute =
  AuthenticatedQuotesQuoteIdEditRouteImport.update({
    id: '/quotes_/$quoteId_/edit',
    path: '/quotes/$quoteId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsItemIdEditRoute =
  AuthenticatedItemsItemIdEditRouteImport.update({
    id: '/items_/$itemId_/edit',
    path: '/items/$itemId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdEditRoute =
  AuthenticatedInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices_/$invoiceId_/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdEditRoute =
  AuthenticatedCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId_/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLocationsLocationIdEditRoute =
  AuthenticatedSettingsLocationsLocationIdEditRouteImport.update({
    id: '/settings_/locations_/$locationId_/edit',
    path: '/settings/locations/$locationId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/items': typeof AuthenticatedItemsRoute
  '/journals': typeof AuthenticatedJournalsRoute
  '/payments-made': typeof AuthenticatedPaymentsMadeRoute
  '/payments-received': typeof AuthenticatedPaymentsReceivedRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/payments-made/$paymentId': typeof AuthenticatedPaymentsMadePaymentIdRoute
  '/payments-made/new': typeof AuthenticatedPaymentsMadeNewRoute
  '/payments-received/$paymentId': typeof AuthenticatedPaymentsReceivedPaymentIdRoute
  '/payments-received/new': typeof AuthenticatedPaymentsReceivedNewRoute
  '/purchase-orders/$poId': typeof AuthenticatedPurchaseOrdersPoIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/sales-orders/$soId': typeof AuthenticatedSalesOrdersSoIdRoute
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/quotes/$quoteId/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/sales-orders/$soId/edit': typeof AuthenticatedSalesOrdersSoIdEditRoute
  '/settings/locations/new': typeof AuthenticatedSettingsLocationsNewRoute
  '/suppliers/$supplierId/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/settings/locations/$locationId/edit': typeof AuthenticatedSettingsLocationsLocationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/items': typeof AuthenticatedItemsRoute
  '/journals': typeof AuthenticatedJournalsRoute
  '/payments-made': typeof AuthenticatedPaymentsMadeRoute
  '/payments-received': typeof AuthenticatedPaymentsReceivedRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/payments-made/$paymentId': typeof AuthenticatedPaymentsMadePaymentIdRoute
  '/payments-made/new': typeof AuthenticatedPaymentsMadeNewRoute
  '/payments-received/$paymentId': typeof AuthenticatedPaymentsReceivedPaymentIdRoute
  '/payments-received/new': typeof AuthenticatedPaymentsReceivedNewRoute
  '/purchase-orders/$poId': typeof AuthenticatedPurchaseOrdersPoIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/sales-orders/$soId': typeof AuthenticatedSalesOrdersSoIdRoute
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/quotes/$quoteId/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/sales-orders/$soId/edit': typeof AuthenticatedSalesOrdersSoIdEditRoute
  '/settings/locations/new': typeof AuthenticatedSettingsLocationsNewRoute
  '/suppliers/$supplierId/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/settings/locations/$locationId/edit': typeof AuthenticatedSettingsLocationsLocationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/banking': typeof AuthenticatedBankingRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/journals': typeof AuthenticatedJournalsRoute
  '/_authenticated/payments-made': typeof AuthenticatedPaymentsMadeRoute
  '/_authenticated/payments-received': typeof AuthenticatedPaymentsReceivedRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/bills_/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/bills_/new': typeof AuthenticatedBillsNewRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/invoices_/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices_/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/items_/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/items_/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/payments-made_/$paymentId': typeof AuthenticatedPaymentsMadePaymentIdRoute
  '/_authenticated/payments-made_/new': typeof AuthenticatedPaymentsMadeNewRoute
  '/_authenticated/payments-received_/$paymentId': typeof AuthenticatedPaymentsReceivedPaymentIdRoute
  '/_authenticated/payments-received_/new': typeof AuthenticatedPaymentsReceivedNewRoute
  '/_authenticated/purchase-orders_/$poId': typeof AuthenticatedPurchaseOrdersPoIdRoute
  '/_authenticated/purchase-orders_/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/quotes_/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/_authenticated/quotes_/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/sales-orders_/$soId': typeof AuthenticatedSalesOrdersSoIdRoute
  '/_authenticated/sales-orders_/new': typeof AuthenticatedSalesOrdersNewRoute
  '/_authenticated/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/_authenticated/settings_/locations': typeof AuthenticatedSettingsLocationsRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/_authenticated/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/customers/$customerId_/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/_authenticated/invoices_/$invoiceId_/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/_authenticated/items_/$itemId_/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/_authenticated/quotes_/$quoteId_/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/_authenticated/sales-orders_/$soId_/edit': typeof AuthenticatedSalesOrdersSoIdEditRoute
  '/_authenticated/settings_/locations_/new': typeof AuthenticatedSettingsLocationsNewRoute
  '/_authenticated/suppliers/$supplierId_/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/_authenticated/settings_/locations_/$locationId_/edit': typeof AuthenticatedSettingsLocationsLocationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/banking'
    | '/bills'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/inventory-adjustments'
    | '/invoices'
    | '/items'
    | '/journals'
    | '/payments-made'
    | '/payments-received'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/sales-orders'
    | '/settings'
    | '/bills/$billId'
    | '/bills/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/items/$itemId'
    | '/items/new'
    | '/payments-made/$paymentId'
    | '/payments-made/new'
    | '/payments-received/$paymentId'
    | '/payments-received/new'
    | '/purchase-orders/$poId'
    | '/purchase-orders/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/sales-orders/$soId'
    | '/sales-orders/new'
    | '/settings/quotes'
    | '/settings/locations'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/customers/'
    | '/suppliers/'
    | '/customers/$customerId/edit'
    | '/invoices/$invoiceId/edit'
    | '/items/$itemId/edit'
    | '/quotes/$quoteId/edit'
    | '/sales-orders/$soId/edit'
    | '/settings/locations/new'
    | '/suppliers/$supplierId/edit'
    | '/settings/locations/$locationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/banking'
    | '/bills'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/inventory-adjustments'
    | '/invoices'
    | '/items'
    | '/journals'
    | '/payments-made'
    | '/payments-received'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/sales-orders'
    | '/settings'
    | '/bills/$billId'
    | '/bills/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/items/$itemId'
    | '/items/new'
    | '/payments-made/$paymentId'
    | '/payments-made/new'
    | '/payments-received/$paymentId'
    | '/payments-received/new'
    | '/purchase-orders/$poId'
    | '/purchase-orders/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/sales-orders/$soId'
    | '/sales-orders/new'
    | '/settings/quotes'
    | '/settings/locations'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/customers'
    | '/suppliers'
    | '/customers/$customerId/edit'
    | '/invoices/$invoiceId/edit'
    | '/items/$itemId/edit'
    | '/quotes/$quoteId/edit'
    | '/sales-orders/$soId/edit'
    | '/settings/locations/new'
    | '/suppliers/$supplierId/edit'
    | '/settings/locations/$locationId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/banking'
    | '/_authenticated/bills'
    | '/_authenticated/chart-of-accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory-adjustments'
    | '/_authenticated/invoices'
    | '/_authenticated/items'
    | '/_authenticated/journals'
    | '/_authenticated/payments-made'
    | '/_authenticated/payments-received'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/quotes'
    | '/_authenticated/reports'
    | '/_authenticated/sales-orders'
    | '/_authenticated/settings'
    | '/_authenticated/bills_/$billId'
    | '/_authenticated/bills_/new'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/customers/new'
    | '/_authenticated/invoices_/$invoiceId'
    | '/_authenticated/invoices_/new'
    | '/_authenticated/items_/$itemId'
    | '/_authenticated/items_/new'
    | '/_authenticated/payments-made_/$paymentId'
    | '/_authenticated/payments-made_/new'
    | '/_authenticated/payments-received_/$paymentId'
    | '/_authenticated/payments-received_/new'
    | '/_authenticated/purchase-orders_/$poId'
    | '/_authenticated/purchase-orders_/new'
    | '/_authenticated/quotes_/$quoteId'
    | '/_authenticated/quotes_/new'
    | '/_authenticated/sales-orders_/$soId'
    | '/_authenticated/sales-orders_/new'
    | '/_authenticated/settings/quotes'
    | '/_authenticated/settings_/locations'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/suppliers/new'
    | '/_authenticated/customers/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/customers/$customerId_/edit'
    | '/_authenticated/invoices_/$invoiceId_/edit'
    | '/_authenticated/items_/$itemId_/edit'
    | '/_authenticated/quotes_/$quoteId_/edit'
    | '/_authenticated/sales-orders_/$soId_/edit'
    | '/_authenticated/settings_/locations_/new'
    | '/_authenticated/suppliers/$supplierId_/edit'
    | '/_authenticated/settings_/locations_/$locationId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders': {
      id: '/_authenticated/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AuthenticatedSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-received': {
      id: '/_authenticated/payments-received'
      path: '/payments-received'
      fullPath: '/payments-received'
      preLoaderRoute: typeof AuthenticatedPaymentsReceivedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-made': {
      id: '/_authenticated/payments-made'
      path: '/payments-made'
      fullPath: '/payments-made'
      preLoaderRoute: typeof AuthenticatedPaymentsMadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journals': {
      id: '/_authenticated/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof AuthenticatedJournalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory-adjustments': {
      id: '/_authenticated/inventory-adjustments'
      path: '/inventory-adjustments'
      fullPath: '/inventory-adjustments'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chart-of-accounts': {
      id: '/_authenticated/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banking': {
      id: '/_authenticated/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AuthenticatedBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/new': {
      id: '/_authenticated/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthenticatedSuppliersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/locations': {
      id: '/_authenticated/settings_/locations'
      path: '/settings/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/quotes': {
      id: '/_authenticated/settings/quotes'
      path: '/quotes'
      fullPath: '/settings/quotes'
      preLoaderRoute: typeof AuthenticatedSettingsQuotesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sales-orders_/new': {
      id: '/_authenticated/sales-orders_/new'
      path: '/sales-orders/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AuthenticatedSalesOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders_/$soId': {
      id: '/_authenticated/sales-orders_/$soId'
      path: '/sales-orders/$soId'
      fullPath: '/sales-orders/$soId'
      preLoaderRoute: typeof AuthenticatedSalesOrdersSoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes_/new': {
      id: '/_authenticated/quotes_/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes_/$quoteId': {
      id: '/_authenticated/quotes_/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders_/new': {
      id: '/_authenticated/purchase-orders_/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders_/$poId': {
      id: '/_authenticated/purchase-orders_/$poId'
      path: '/purchase-orders/$poId'
      fullPath: '/purchase-orders/$poId'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersPoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-received_/new': {
      id: '/_authenticated/payments-received_/new'
      path: '/payments-received/new'
      fullPath: '/payments-received/new'
      preLoaderRoute: typeof AuthenticatedPaymentsReceivedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-received_/$paymentId': {
      id: '/_authenticated/payments-received_/$paymentId'
      path: '/payments-received/$paymentId'
      fullPath: '/payments-received/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsReceivedPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-made_/new': {
      id: '/_authenticated/payments-made_/new'
      path: '/payments-made/new'
      fullPath: '/payments-made/new'
      preLoaderRoute: typeof AuthenticatedPaymentsMadeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-made_/$paymentId': {
      id: '/_authenticated/payments-made_/$paymentId'
      path: '/payments-made/$paymentId'
      fullPath: '/payments-made/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsMadePaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items_/new': {
      id: '/_authenticated/items_/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items_/$itemId': {
      id: '/_authenticated/items_/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/new': {
      id: '/_authenticated/invoices_/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/$invoiceId': {
      id: '/_authenticated/invoices_/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills_/new': {
      id: '/_authenticated/bills_/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AuthenticatedBillsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills_/$billId': {
      id: '/_authenticated/bills_/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$supplierId_/edit': {
      id: '/_authenticated/suppliers/$supplierId_/edit'
      path: '/suppliers/$supplierId/edit'
      fullPath: '/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/locations_/new': {
      id: '/_authenticated/settings_/locations_/new'
      path: '/settings/locations/new'
      fullPath: '/settings/locations/new'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders_/$soId_/edit': {
      id: '/_authenticated/sales-orders_/$soId_/edit'
      path: '/sales-orders/$soId/edit'
      fullPath: '/sales-orders/$soId/edit'
      preLoaderRoute: typeof AuthenticatedSalesOrdersSoIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes_/$quoteId_/edit': {
      id: '/_authenticated/quotes_/$quoteId_/edit'
      path: '/quotes/$quoteId/edit'
      fullPath: '/quotes/$quoteId/edit'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items_/$itemId_/edit': {
      id: '/_authenticated/items_/$itemId_/edit'
      path: '/items/$itemId/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/$invoiceId_/edit': {
      id: '/_authenticated/invoices_/$invoiceId_/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId_/edit': {
      id: '/_authenticated/customers/$customerId_/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/locations_/$locationId_/edit': {
      id: '/_authenticated/settings_/locations_/$locationId_/edit'
      path: '/settings/locations/$locationId/edit'
      fullPath: '/settings/locations/$locationId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsQuotesRoute: typeof AuthenticatedSettingsQuotesRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsQuotesRoute: AuthenticatedSettingsQuotesRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBankingRoute: typeof AuthenticatedBankingRoute
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedChartOfAccountsRoute: typeof AuthenticatedChartOfAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryAdjustmentsRoute: typeof AuthenticatedInventoryAdjustmentsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedJournalsRoute: typeof AuthenticatedJournalsRoute
  AuthenticatedPaymentsMadeRoute: typeof AuthenticatedPaymentsMadeRoute
  AuthenticatedPaymentsReceivedRoute: typeof AuthenticatedPaymentsReceivedRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesOrdersRoute: typeof AuthenticatedSalesOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedBillsNewRoute: typeof AuthenticatedBillsNewRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedPaymentsMadePaymentIdRoute: typeof AuthenticatedPaymentsMadePaymentIdRoute
  AuthenticatedPaymentsMadeNewRoute: typeof AuthenticatedPaymentsMadeNewRoute
  AuthenticatedPaymentsReceivedPaymentIdRoute: typeof AuthenticatedPaymentsReceivedPaymentIdRoute
  AuthenticatedPaymentsReceivedNewRoute: typeof AuthenticatedPaymentsReceivedNewRoute
  AuthenticatedPurchaseOrdersPoIdRoute: typeof AuthenticatedPurchaseOrdersPoIdRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedSalesOrdersSoIdRoute: typeof AuthenticatedSalesOrdersSoIdRoute
  AuthenticatedSalesOrdersNewRoute: typeof AuthenticatedSalesOrdersNewRoute
  AuthenticatedSettingsLocationsRoute: typeof AuthenticatedSettingsLocationsRoute
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRoute
  AuthenticatedSuppliersNewRoute: typeof AuthenticatedSuppliersNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedCustomersCustomerIdEditRoute: typeof AuthenticatedCustomersCustomerIdEditRoute
  AuthenticatedInvoicesInvoiceIdEditRoute: typeof AuthenticatedInvoicesInvoiceIdEditRoute
  AuthenticatedItemsItemIdEditRoute: typeof AuthenticatedItemsItemIdEditRoute
  AuthenticatedQuotesQuoteIdEditRoute: typeof AuthenticatedQuotesQuoteIdEditRoute
  AuthenticatedSalesOrdersSoIdEditRoute: typeof AuthenticatedSalesOrdersSoIdEditRoute
  AuthenticatedSettingsLocationsNewRoute: typeof AuthenticatedSettingsLocationsNewRoute
  AuthenticatedSuppliersSupplierIdEditRoute: typeof AuthenticatedSuppliersSupplierIdEditRoute
  AuthenticatedSettingsLocationsLocationIdEditRoute: typeof AuthenticatedSettingsLocationsLocationIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBankingRoute: AuthenticatedBankingRoute,
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedChartOfAccountsRoute: AuthenticatedChartOfAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryAdjustmentsRoute:
    AuthenticatedInventoryAdjustmentsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedJournalsRoute: AuthenticatedJournalsRoute,
  AuthenticatedPaymentsMadeRoute: AuthenticatedPaymentsMadeRoute,
  AuthenticatedPaymentsReceivedRoute: AuthenticatedPaymentsReceivedRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesOrdersRoute: AuthenticatedSalesOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedBillsNewRoute: AuthenticatedBillsNewRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedPaymentsMadePaymentIdRoute:
    AuthenticatedPaymentsMadePaymentIdRoute,
  AuthenticatedPaymentsMadeNewRoute: AuthenticatedPaymentsMadeNewRoute,
  AuthenticatedPaymentsReceivedPaymentIdRoute:
    AuthenticatedPaymentsReceivedPaymentIdRoute,
  AuthenticatedPaymentsReceivedNewRoute: AuthenticatedPaymentsReceivedNewRoute,
  AuthenticatedPurchaseOrdersPoIdRoute: AuthenticatedPurchaseOrdersPoIdRoute,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedSalesOrdersSoIdRoute: AuthenticatedSalesOrdersSoIdRoute,
  AuthenticatedSalesOrdersNewRoute: AuthenticatedSalesOrdersNewRoute,
  AuthenticatedSettingsLocationsRoute: AuthenticatedSettingsLocationsRoute,
  AuthenticatedSuppliersSupplierIdRoute: AuthenticatedSuppliersSupplierIdRoute,
  AuthenticatedSuppliersNewRoute: AuthenticatedSuppliersNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedCustomersCustomerIdEditRoute:
    AuthenticatedCustomersCustomerIdEditRoute,
  AuthenticatedInvoicesInvoiceIdEditRoute:
    AuthenticatedInvoicesInvoiceIdEditRoute,
  AuthenticatedItemsItemIdEditRoute: AuthenticatedItemsItemIdEditRoute,
  AuthenticatedQuotesQuoteIdEditRoute: AuthenticatedQuotesQuoteIdEditRoute,
  AuthenticatedSalesOrdersSoIdEditRoute: AuthenticatedSalesOrdersSoIdEditRoute,
  AuthenticatedSettingsLocationsNewRoute:
    AuthenticatedSettingsLocationsNewRoute,
  AuthenticatedSuppliersSupplierIdEditRoute:
    AuthenticatedSuppliersSupplierIdEditRoute,
  AuthenticatedSettingsLocationsLocationIdEditRoute:
    AuthenticatedSettingsLocationsLocationIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
